source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3", ">= 7.0.3.1"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"
gem 'bcrypt', '~> 3.1.7'
# API framework
gem 'grape' # grape for the API facade
gem 'grape-entity' # data tranfer transformer
gem 'grape-swagger' # API documentation
gem 'grape-swagger-rails' # UI for swagger

# Auth / user management
gem 'devise' # user auth framework...
gem 'jwt'
gem 'active_model_serializers'
gem 'faker'
group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring" #Spring is a Rails application preloader
  gem "sprockets-rails"#Ruby library for compiling and serving web assets
  gem 'better_errors'
  gem 'byebug'
  gem 'database_cleaner'
  gem 'rails_best_practices'
  gem 'rubocop'
  gem 'rubocop-faker'
  gem 'rubocop-rails'
  gem 'simplecov', require: false #code coverage for ruby
  gem 'listen'
  gem 'factory_bot'
  gem 'factory_bot_rails'
  #gem 'faker'
  gem 'i18n'
  gem 'minitest' #Testing 
  gem 'minitest-around'
  gem 'webmock' #Library for stubbing and setting expectations on HTTP requests in Ruby
end

